name: spm-stack

volumes:
  pgdata:
    name: spm_pgdata

networks:
  spm-net:
    driver: bridge
    name: spm-net

services:
  kong:
    image: kong/kong-gateway:3.9.0.1
    container_name: kong-dbless
    restart: always
    networks:
      - spm-net
    volumes:
      - ./backend/kong:/kong/declarative
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_LICENSE_DATA: ""
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - spm-net
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - spm-net
    ports:
      - "1010:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards

  manage-account:
    build:
      context: ./backend/services/composite/manage-account
      dockerfile: dockerfile
    container_name: manage-account
    restart: unless-stopped
    networks:
      - spm-net
    ports:
      - "8090:8090"

  manage-task:
    build:
      context: ./backend/services/composite/manage-task
      dockerfile: dockerfile
    container_name: manage-task
    restart: unless-stopped
    networks:
      - spm-net
    ports:
      - "8091:8091"

  organise-project:
    build:
      context: ./backend/services/composite/organise-project
      dockerfile: dockerfile
    container_name: organise-project
    restart: unless-stopped
    networks:
      - spm-net
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - project

  profile:
    build:
      context: ./backend/services/atomic/profile
      dockerfile: dockerfile
    container_name: profile
    restart: unless-stopped
    networks:
      - spm-net
    env_file:
      - ./backend/services/atomic/profile/.env
    ports:
      - "3030:3030"
    environment:
      PORT: "3030"
      FE_ENDPOINT: "http://localhost:5173"

  task:
    build:
      context: ./backend/services/atomic/task
      dockerfile: dockerfile
    container_name: task
    restart: unless-stopped
    networks:
      - spm-net
    env_file:
      - ./backend/services/atomic/task/.env
    ports:
      - "3031:3031"
    environment:
      PORT: "3031"
      FE_ENDPOINT: "http://localhost:5173"
  project:
      build:
        context: ./backend/services/atomic/project
        dockerfile: dockerfile
      container_name: project
      restart: unless-stopped
      networks:
        - spm-net
      env_file:
        - ./backend/services/atomic/project/.env
      ports:
        - "3040:3040"
      environment:
        PORT: "3040"
        FE_ENDPOINT: "http://localhost:5173"  


