name: Backend Unit Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  profile_tests:
    name: Node — atomic/profile tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/services/atomic/profile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/services/atomic/profile/package-lock.json
      - run: npm ci
      - run: npm test -- --coverage

  manage_account_tests:
    name: Go — composite/manage-account tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/services/composite/manage-account
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test ./... -race -covermode=atomic -coverprofile=coverage.out
